### ISSUE TITLE
Installed TA list on a device, at the TAM or TEEP device

### ISSUE THREAD

**Issue by mcd500** [ietf-teep/architecture#149]
This is just clarification of something we came across when we were prototyping TEEP.

Initially I only had two scenarios bellow in my mind.

TAM maintains the list of which Device have installed TA (by taname, uuid or any method to identity).
Or TEEP-Agent (or TEEP-Broker for less security) have the list of installed TA on Device.

But it may able be OK for both TAM and TEEP-Agent do not keep tracking the list of installed TA on Device.

For example on op-tee, after the TA are stored to secure storage. But it does not have an API to retrieve the TAs installed in the past. So if TEEP-Agent or TEEP-Broker are not tracking the TA installed or deleted, then it may keep asking the TAM for the TA binary which causes network bandwidth overhead,  or keep asking the TAM for delete the TA repeatedly which might be similar to DDOS for the TAM.

Then it looks mandatory or recommended for the TAM maintaining the list of which Device have installed/deleted which TAs.

**Comment by dthaler** [comment]
> But it may able be OK for both TAM and TEEP-Agent do not keep tracking the list of installed TA on Device.

Correct, there is no such requirement. 

For the TAM, that's why there's a GetDeviceState message for the TAM to ask if/when it needs to, so it need not store state.

For the device, David Wheeler explained in some previous WG presentation about SGX that there is no way to enumerate all installed TAs for SGX.  A particular TEEP Agent will know of some (e.g., a TEEP Agent servicing a particular Untrusted App might know about all the TAs associated with that Untrusted App).

Multiple TEEP Agents on the same device might (in some implementations) install the same TA multiple times, such as if SGX TA's are stored next to Untrusted Apps on the filesystem, so multiple independent installs can be fine.

All that is required is that a TEEP Agent know what TAs are installed for the scope of that TEEP Agent.

> For example on op-tee, after the TA are stored to secure storage. But it does not have an API to retrieve the TAs installed in the past. 

FYI, in Microsoft's prototyping efforts, we can enumerate what TAs are installed on OP-TEE, and we can also enumerate what "files" are stored to secure storage so it is possible on top of OP-TEE.

**Comment by kunisuzaki** [comment]
The slide used by David Wheeler is the following?
"Recommendations for TEEP Support of Intel® SGX Technology"
https://datatracker.ietf.org/meeting/102/materials/slides-102-teep-recommendations-for-teep-support-of-intel-sgx-technology-02

Page15 "SGX TA Install with TEEP Agent" shows a "TEE Agent" on REE with "TEE Agent Enclave" on TEE.
If the TEE Agent runs as a deamon, it keeps tracking the list of installed TAs.
if not, it cannot keep the list of installed TAs.

**Comment by dthaler** [comment]
There is, however, an assumption that a TEEP Agent can tell whether a given TA is installed in the TEE or not, even if it cannot enumerate them.  For example, if a rich app wants to call into a TA, something has to make sure it's loaded and can make the actually invocation.   That by itself should be sufficient to prevent a TEEP Agent from asking the TAM to install a TA that is already installed.

**Comment by mcd500** [comment]
@dthaler @kunisuzaki Thanks!
