### ISSUE TITLE
Section 8: revise Asymmetric and symmetric algorithms usage

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#182]
Russ commented:

     18) Section 18: Asymmetric algorithms are also used to manage the symmetric keys.  Symmetric algorithms are also used for data integrity.

MP: will revise it to reflect both points.

Symmetric algorithms are used for encryption
   of content whereas the asymmetric algorithms are mostly used for
   signing messages.

==>

Symmetric algorithms are used for encryption
   of content and data integrity whereas the asymmetric algorithms are used for
   signing messages and managing symmetric keys.

Russ: thanks...

**Comment by dthaler** [comment]
PR #168 is addressing this

**Comment by dthaler** [comment]
Fixed in draft-09

**Comment by tireddy2** [comment]
The updated text in Section 8 does not discuss data integrity using symmetric algorithms (e.g., AEAD, see https://tools.ietf.org/html/rfc5116).

**Comment by dthaler** [comment]
@hannestschofenig can you check Tiru's question?

**Comment by dthaler** [comment]
In discussion of Tiru's question, Tiru elaborated:
> My comment is If the TEEP protocol is using AEAD for encryption, 
> message authentication is implicit (MAC need not be explicitly 
> computed). I think you are saying the message will have two MACs 
> (one from AEAD and the other from the asymmetric key).

And David Wheeler answered:
> The AEAD MAC is good only for integrity; it does not provide proof-of-source.
> I believe that our messages require (in some instances) 
> proof-of-source for the attestation. This is the reason for two MACs.

And Tiru responded:
> You may want to add more details to the draft for clarity and discuss the attacks possible to justify two MACs.

**Comment by hannestschofenig** [comment]
Regarding the two MACs: 

There are two layers of protection provided: 
1) TEEP message protection, and 
2) payload protection (for example personalization data, and trusted app binaries using SUIT, attestation data using EAT or something)

Besides the endpoints being different for the protection of the messages vs. the payloads, there is not necessarily the same security primitive used at the two layers. 

IMHO these differences should be clear from the overall document because that's one of the core architectural aspects being discussed in the document. If that's not clear, we should do some major surgery on the document...

**Comment by dthaler** [comment]
@tireddy2 can you confirm that the answer above plus the changes from PR #209 that were just merged would be sufficient in your opinion to close this issue?

**Comment by dthaler** [comment]
Fixed in draft-13

**Comment by tireddy2** [comment]
Update looks good.
