### ISSUE TITLE
Definitions of Trust Anchor and Trust Anchor Store

### ISSUE THREAD

**Issue by mingpeiwk** [ietf-teep/architecture#51]
Trust Anchors are typically a list of Certification Authority (CA) certificate. It can be also public key of a trusted authority and identifier. Trust Anchors are assumed to be implemented by TEEs. The format of list or public key are assumed to be the well known format such as X.509 certificate.

A specific format to define such a list for Trust Anchor update is considered also out of scope for TEEP architecture. This may be worthy some consideration for a later separate draft as an advanced feature.

**Comment by dmwheel1** [comment]
In my view, a Trust Anchor is a 
* a unique identifier for a trusted entity that is used to select a verification key for that entity
* a trust anchor resists replacement, modification or corruption by an adversary

An X.509 certificate by itself does not fulfill the second criteria, as by itself it cannot resist replacement. 
Some mechanism to protect the key must be used. A typical example is fuses - a hash of the public exponent and modulus of an RSA key is put in fuses. Then either an X.509 certificate or even just a raw RSA key, can be used as the trust anchor. The fuses are set during manufacturing or some post manufacturing process, by a trusted entity (manufacturer, device admin, device owner, etc.).
The hash of the public key and modulus is typically referred to as a FINGERPRINT.

One recommended approach to a trust anchor list is for the device manufacturer to provision a hash of the RAW RSA key into fuses (it can be any type of key, ECDSA if you prefer, but we will use RSA for the example). The private RSA key is held by the trusted entity.  Trusted keys can be issued at any time by the trusted entity by putting the new trusted key into an X.509 certificate and signing that certificate with the Trust Anchor key. The device can check if this new key it receives is trustable, by verifying the certificate is signed by a key whose hash matches the hash in fuses.

We must be clear that there are can many ways to create a Trust Anchor list. X.509 certificates are not required. Fuses are not required. I can use locked Flash blocks. I could also use encrypted battery-backed RAM. I could use separate flash accessible only to a TEE. Many, Many ways are possible.

We must identify ONLY the REQUIREMENTS for the trust anchor, and their usage. Examples are fine to provide, but the requirements are the basis, so we allow different implementations.

**Comment by dthaler** [comment]
Here’s what https://tools.ietf.org/html/draft-ietf-suit-architecture-03 currently says:

   The terms 'trust anchor' and 'trust anchor store' are defined in
   [RFC6024<https://tools.ietf.org/html/rfc6024>]:

   -  "A trust anchor represents an authoritative entity via a public
      key and associated data.  The public key is used to verify digital
      signatures, and the associated data is used to constrain the types
      of information for which the trust anchor is authoritative."

   -  "A trust anchor store is a set of one or more trust anchors stored
      in a device.  A device may have more than one trust anchor store,
      each of which may be used by one or more applications."

As co-chair of both WG’s, I’d suggest that the teep arch doc and the suit arch doc be consistent.

Dave

**Comment by dmwheel1** [comment]
I agree with the definition as posted, but I believe that there is a requirement missing.

Specifically, a trsut anchor store must resist modification against unauthorized insertion, deletion, and modification. Without such a requirement, a plain-text file on my file system containing X.509 certificates would be a trust anchor store. Any attacker on the platform can add new trusted certificates and remove other trusted certificates. This does not meet the minimal requirements for TEEP, because if any modification is performed to the trust anchor store that can change the management of the TAs.

Perhaps there is an underlying assumption that the trust anchor store is kept within the TEE. But that is not stated in the discussion. However, mandating the store be inside the TEE is restrictive of implementations. In some renditions I am aware of, the trust anchor store is kept by a separate entity outside the TEE, and there is a trusted channel between the TEE and the store.

Therefore, I think the definition @DaveThaler provided needs to be updated to include security requirements on the protection and management of the store.

**Comment by amichalas** [comment]
I agree with dmwheel. On top of that, running a trust anchor in a TEE might be an issue due to several restrictions. However, in an ideal world using a TEE for that would be the best way to go. In case though you do not use a TEE then an integrity verification mechanism should be in place. Hence, it might be good to describe two different cases: 
1. Trust anchor is running in a TEE. 
2. Trust anchor is running outside of a TEE.

**Comment by dthaler** [comment]
draft-ietf-teep-architecture-03 includes section
5.8.  Trust Anchors in TEE
which talks about keeping them in the TEE.

Also, the suit architecture was updated with David's point so now adds "A trust
      anchor store must resist modification against unauthorized
      insertion, deletion, and modification."

Can we just match SUIT's definitions now (in draft-ietf-suit-architecture-07
 section 2)?  Should we copy them or reference them, now that we depend on SUIT?

**Comment by dthaler** [comment]
I'd like to call out that the proposed text takes a different approach than the sense of the room in Singapore.  From the meeting minutes "Options for aligning TA storage requirements with SUIT - incorporate by reference or by text - sense of room is by reference."

I tried doing it by reference, but it turned out to be too hard to reference SUIT manifest for definitions of the trust anchor and trust anchor store because the TEEP architecture already had a definition in it that was referenced internally, and because TEEPs use of trust anchors itself is     independent of its use of a SUIT manifest.  Hence copied in duplicate text, and also referenced the SUIT manifest as having the same definition.
