### ISSUE TITLE
Figure 6: Difference between "Device secure storage" and "Device TEE" unclear

### ISSUE THREAD

**Issue by nicopal** [ietf-teep/architecture#58]
Column "Location" in Figure 6: Key and Certificate Types contains both "Device secure storage" and "Device TEE". I suspect they are intended to mean the same thing and this must be reflected in the text. 

Suggestion: use the term "Device TEE"

**Comment by dthaler** [comment]
I suspect they are not necessarily the same thing, especially if the device has more than one TEE (compare issue #30).  For example, in some cases the "device secure storage" might be ROM, if the lifetime of the hardware is less than the lifetime of the TFW certificate.
Can other authors confirm?

If the distinction is intentional, then adding a sentence to explain would be helpful.
